export const RoutePaths = {
  HOME: '/',
  LOGIN: '/login',
  MICROSOFT_CALLBACK: '/auth/microsoft-callback',
  DASHBOARD: '/dashboard',
  PROJECTS: '/projects',
  PROJECT_DETAIL: (id: string) => `/projects/${id}`,
  BACKLOG: '/backlog',
  EPICS: '/epics',
  EPIC_DETAIL: (id: string) => `/epics/${id}`,
  STORIES: '/stories',
  STORY_DETAIL: (id: string) => `/stories/${id}`,
  TASKS: '/tasks',
  TASK_DETAIL: (id: string) => `/tasks/${id}`,
  BUGS: '/bugs',
  SPRINTS: '/sprints',
  KANBAN: '/kanban',
  LIST: '/list',
  USERS: '/users',
  NOT_FOUND: '*',
} as const;
